import { SiteHeader } from "@/components/site-header";
import { SiteFooter } from "@/components/site-footer";
import { NewsletterForm } from "@/components/forms";
import { AcademyArchitecture } from "@/components/academy-architecture";
import { GuideSection } from "@/components/guide-section";

export default function Home(){return <><SiteHeader/><main id="main">
  <section className="hero"><div className="shell hero-inner"><p className="eyebrow">Professional learning · Across globe</p><h1 className="display">Move forward with clarity.</h1><p>Practical academies for people ready to build modern skills, lead better, and take on greater responsibility.</p><div className="action-row"><a className="btn btn-gold" href="/programmes#academy-architecture" target="_self">Explore programmes</a><a className="btn btn-ghost" href="/contact#booking" target="_self">Book a conversation</a></div><div className="hero-note"><div><strong>Built for work</strong><span>Apply learning to real professional situations.</span></div><div><strong>Designed for progress</strong><span>Focused capability, practical implementation.</span></div></div></div></section>
  <section className="section" id="academies"><div className="shell"><div className="section-head"><div><p className="eyebrow">Academy architecture</p><h2 className="display">One parent brand. Five focused academies.</h2></div><p>Choose the academy that matches the capability you want to build. Each one has a distinct learner promise and shares AccelPro’s practical operating backbone.</p></div><AcademyArchitecture compact/></div></section>
  <section className="section section-dark"><div className="shell"><div className="section-head"><div><p className="eyebrow">The difference</p><h2 className="display">Clarity before complexity.</h2></div><p>AccelPro Academy is built for adults with real constraints, experience, and ambition. The work starts with context and ends with practical application.</p></div><div className="benefits"><div className="benefit"><span>01</span><h3>Relevant</h3><p>Learning connected to the situations you already face.</p></div><div className="benefit"><span>02</span><h3>Structured</h3><p>A clear path from understanding to practice.</p></div><div className="benefit"><span>03</span><h3>Challenging</h3><p>Thoughtful questions that sharpen judgement.</p></div><div className="benefit"><span>04</span><h3>Usable</h3><p>Tools and decisions you can take back to work.</p></div></div></div></section>
  <section className="section"><div className="shell"><div className="section-head"><div><p className="eyebrow">How it works</p><h2 className="display">A simple path to the right programme.</h2></div><p>Begin with your goal, identify the relevant academy, then choose the right learning format.</p></div><div className="process"><div className="step"><h3>Share your context</h3><p>Tell us what you are working towards and where progress feels difficult.</p></div><div className="step"><h3>Choose the fit</h3><p>Review the academy, learner promise, and programme options.</p></div><div className="step"><h3>Apply the learning</h3><p>Use the ideas and tools in situations that matter to your work.</p></div></div></div></section>
  <GuideSection/>
  <section className="section section-maroon"><div className="shell quote-band"><div><p className="eyebrow">Start here</p><h2 className="display">Not sure which programme fits?</h2><p>Share your goal. We’ll help you identify the most relevant next step.</p></div><div><a className="btn btn-gold" href="/contact#booking">Talk to the academy</a></div></div></section>
  <section className="section"><div className="shell"><div className="section-head"><div><p className="eyebrow">Common questions</p><h2 className="display">Useful answers before you enquire.</h2></div></div><div className="faq"><details><summary>Who are the academies for?</summary><p>They are designed for working professionals, managers, founders, specialists, and teams building practical capability.</p></details><details><summary>Are programmes online or in person?</summary><p>Delivery mode, location, duration, and schedule vary by programme. Ask about the academy that interests you for the current options.</p></details><details><summary>Can organisations arrange a cohort?</summary><p>Use the contact form to describe your team, capability need, and preferred timeline.</p></details><details><summary>How do I choose an academy?</summary><p>Browse the learner outcomes first. If two or more appear relevant, book a short conversation and share the professional situation you want to improve.</p></details></div></div></section>
  <section className="section-sm newsletter-band"><div className="shell newsletter"><div><p className="eyebrow">Stay informed</p><h2 className="display">New programmes. Useful ideas. No noise.</h2></div><NewsletterForm/></div></section>
 </main><SiteFooter/></>}
