"use client";
import { FormEvent, useState } from "react";
import { courses } from "@/lib/courses";

type Status = {kind:"idle"|"success"|"error"; text:string};
async function submit(endpoint:string, data:Record<string,string>){const r=await fetch(endpoint,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(data)});const body=await r.json() as {message?:string,error?:string};if(!r.ok) throw new Error(body.error||"We could not submit this form.");return body.message||"Submitted successfully."}

export function EnquiryForm({initialProgramme=""}:{initialProgramme?:string}){const [busy,setBusy]=useState(false);const [status,setStatus]=useState<Status>({kind:"idle",text:""});async function onSubmit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setStatus({kind:"idle",text:""});const form=e.currentTarget;try{const data=Object.fromEntries(new FormData(form).entries()) as Record<string,string>;const message=await submit("/api/enquiries",data);form.reset();setStatus({kind:"success",text:message})}catch(err){setStatus({kind:"error",text:err instanceof Error?err.message:"Submission failed."})}finally{setBusy(false)}}return <form onSubmit={onSubmit}><div className="honeypot" aria-hidden="true"><label htmlFor="enquiry-website">Website</label><input id="enquiry-website" name="website" tabIndex={-1} autoComplete="off" /></div><div className="form-grid"><div className="field"><label htmlFor="name">Name</label><input id="name" name="name" required autoComplete="name" /></div><div className="field"><label htmlFor="email">Email ID</label><input id="email" name="email" type="email" required autoComplete="email" /></div><div className="field"><label htmlFor="phone">Phone number</label><input id="phone" name="phone" type="tel" autoComplete="tel" /></div><div className="field"><label htmlFor="programme">Programme of interest</label><select id="programme" name="programme" defaultValue={initialProgramme}><option value="">Not sure yet</option>{courses.map(c=><option key={c.title}>{c.title}</option>)}</select></div><div className="field full"><label htmlFor="message">What would you like help with?</label><textarea id="message" name="message" minLength={15} required /></div></div><button disabled={busy} className="btn btn-primary form-submit" type="submit">{busy?"Sending…":"Send enquiry"}</button><p className={`form-status ${status.kind}`} role="status">{status.text}</p></form>}

export function BookingForm(){const [busy,setBusy]=useState(false);const [status,setStatus]=useState<Status>({kind:"idle",text:""});async function onSubmit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setStatus({kind:"idle",text:""});const form=e.currentTarget;try{const data=Object.fromEntries(new FormData(form).entries()) as Record<string,string>;const message=await submit("/api/bookings",data);form.reset();setStatus({kind:"success",text:message})}catch(err){setStatus({kind:"error",text:err instanceof Error?err.message:"Request failed."})}finally{setBusy(false)}}return <form onSubmit={onSubmit}><div className="honeypot" aria-hidden="true"><label htmlFor="booking-website">Website</label><input id="booking-website" name="website" tabIndex={-1} autoComplete="off" /></div><div className="form-grid"><div className="field"><label htmlFor="booking-name">Name</label><input id="booking-name" name="name" required autoComplete="name" /></div><div className="field"><label htmlFor="booking-email">Email ID</label><input id="booking-email" name="email" type="email" required autoComplete="email" /></div><div className="field full"><label htmlFor="booking-phone">Phone number</label><input id="booking-phone" name="phone" type="tel" required autoComplete="tel" /></div><label className="consent-row full" htmlFor="whatsapp-opt-in"><input id="whatsapp-opt-in" name="whatsappOptIn" type="checkbox" value="yes"/><span>Send me updates from AccelPro Digital Marketing Academy on WhatsApp. I can stop them any time.</span></label></div><button disabled={busy} className="btn btn-primary form-submit" type="submit">{busy?"Booking…":"Book now"}</button><p className={`form-status ${status.kind}`} role="status">{status.text}</p><p className="form-note">We’ll use these details to arrange your conversation. See our <a href="/privacy">privacy notice</a>.</p></form>}

export function NewsletterForm({compact=false}:{compact?:boolean}){const [busy,setBusy]=useState(false);const [status,setStatus]=useState<Status>({kind:"idle",text:""});async function onSubmit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);const form=e.currentTarget;try{const data=Object.fromEntries(new FormData(form).entries()) as Record<string,string>;const message=await submit("/api/newsletter",data);form.reset();setStatus({kind:"success",text:message})}catch(err){setStatus({kind:"error",text:err instanceof Error?err.message:"Signup failed."})}finally{setBusy(false)}}return <form onSubmit={onSubmit}><div className="honeypot" aria-hidden="true"><label htmlFor={compact?"footer-website":"newsletter-website"}>Website</label><input id={compact?"footer-website":"newsletter-website"} name="website" tabIndex={-1} autoComplete="off" /></div><div className="inline-form"><label className="sr-only" htmlFor={compact?"footer-email":"newsletter-email"}>Email address</label><input id={compact?"footer-email":"newsletter-email"} name="email" type="email" required placeholder="you@company.com" autoComplete="email"/><button className={`btn ${compact?"btn-gold":"btn-primary"}`} disabled={busy}>{busy?"Joining…":"Join the list"}</button></div><p className={`form-status ${status.kind}`} role="status">{status.text}</p></form>}
